export interface Post {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  categoryName: string;
  author: string;
  authorRole: string;
  date: string;
  readTime: number;
  tags: string[];
  coverEmoji: string;
}

const POSTS: Post[] = [
  {
    slug: 'como-reduzir-faltas-agendamentos',
    title: 'Como Reduzir Faltas e No-Shows na Sua Clínica em até 60%',
    excerpt: 'Descubra estratégias comprovadas de confirmação automática, listas de espera e política de cancelamento para maximizar a ocupação da sua agenda.',
    content: `<h2>O Problema das Faltas na Clínica</h2><p>As faltas não comunicadas (no-shows) representam, em média, 18% das consultas agendadas em clínicas brasileiras.</p><h2>1. Confirmação Automática Multicanal</h2><p>Implemente lembretes automáticos por WhatsApp, SMS e e-mail em três momentos: 48h, 24h e 2h antes da consulta.</p><h2>2. Lista de Espera Inteligente</h2><p>Quando um paciente cancela, o sistema deve notificar automaticamente os próximos da lista de espera.</p>`,
    category: 'gestao-financeira',
    categoryName: 'Gestão Financeira',
    author: 'Equipe NexusMed',
    authorRole: 'Time de Conteúdo',
    date: '2026-03-08',
    readTime: 5,
    tags: ['agendamento', 'produtividade', 'receita'],
    coverEmoji: '📅',
  },
  {
    slug: 'fluxo-de-caixa-clinica',
    title: 'Fluxo de Caixa para Clínicas: Como Montar, Controlar e Não Quebrar',
    excerpt: 'Guia completo para estruturar o fluxo de caixa da sua clínica, antecipar crise de liquidez e garantir capital de giro.',
    content: `<h2>Por que o Fluxo de Caixa é Vital</h2><p>Muitas clínicas lucrativas fecham as portas por falta de liquidez.</p><h2>Reserva de Emergência</h2><p>Mantenha 3 meses de custos fixos em conta separada.</p>`,
    category: 'gestao-financeira',
    categoryName: 'Gestão Financeira',
    author: 'Equipe NexusMed',
    authorRole: 'Gestão Financeira',
    date: '2026-03-07',
    readTime: 8,
    tags: ['fluxo de caixa', 'liquidez', 'capital de giro'],
    coverEmoji: '🏦',
  },
  {
    slug: 'precificacao-de-procedimentos',
    title: 'Como Precificar Procedimentos Médicos sem Trabalhar no Prejuízo',
    excerpt: 'Aprenda a calcular o preço justo dos seus procedimentos considerando custos diretos, indiretos, pró-labore e margem.',
    content: `<h2>O Erro Mais Comum</h2><p>A maioria dos médicos precifica baseando-se no concorrente, sem calcular se o valor cobre os custos.</p>`,
    category: 'gestao-financeira',
    categoryName: 'Gestão Financeira',
    author: 'Equipe NexusMed',
    authorRole: 'Gestão Financeira',
    date: '2026-03-04',
    readTime: 9,
    tags: ['precificação', 'custos', 'margem'],
    coverEmoji: '💲',
  },
  {
    slug: 'glosas-de-convenios-como-reduzir',
    title: 'Glosas de Convênios: Como Reduzir para Menos de 3%',
    excerpt: 'Causas, impacto financeiro e como estruturar o processo de faturamento para minimizar glosas.',
    content: `<h2>O Que é Glosa</h2><p>Glosa é a negativa de pagamento do plano. A média no Brasil é de 8-12% do faturamento com convênios.</p>`,
    category: 'gestao-financeira',
    categoryName: 'Gestão Financeira',
    author: 'Equipe NexusMed',
    authorRole: 'Faturamento & Convênios',
    date: '2026-02-28',
    readTime: 7,
    tags: ['glosa', 'convênios', 'faturamento'],
    coverEmoji: '📝',
  },
  {
    slug: 'prontuario-eletronico-como-escolher',
    title: 'Prontuário Eletrônico: Como Escolher o Sistema Certo para Sua Clínica',
    excerpt: 'Comparativo dos principais critérios para avaliar um PEP: usabilidade, integração com TISS, suporte e segurança.',
    content: `<h2>Por que o PEP Certo Faz Diferença</h2><p>O PEP é o coração da operação clínica. Um sistema mal escolhido gera retrabalho.</p>`,
    category: 'tecnologia-em-saude',
    categoryName: 'Tecnologia em Saúde',
    author: 'Equipe NexusMed',
    authorRole: 'Produto & Tecnologia',
    date: '2026-03-01',
    readTime: 7,
    tags: ['PEP', 'tecnologia', 'software'],
    coverEmoji: '💻',
  },
  {
    slug: 'telemedicina-guia-completo-clinicas',
    title: 'Telemedicina para Clínicas: Guia Completo para Implementar com Segurança',
    excerpt: 'Da regulamentação CFM à escolha da plataforma: tudo que sua clínica precisa saber.',
    content: `<h2>Telemedicina é Legal no Brasil?</h2><p>Sim. A Resolução CFM 2.314/22 regulamentou definitivamente a telemedicina no Brasil.</p>`,
    category: 'tecnologia-em-saude',
    categoryName: 'Tecnologia em Saúde',
    author: 'Equipe NexusMed',
    authorRole: 'Produto & Tecnologia',
    date: '2026-03-06',
    readTime: 8,
    tags: ['telemedicina', 'CFM', 'videoconsulta'],
    coverEmoji: '📹',
  },
  {
    slug: 'ia-na-saude-o-que-muda-para-clinicas',
    title: 'IA na Saúde: O Que Muda na Prática para Clínicas e Consultórios',
    excerpt: 'Como a inteligência artificial está transformando diagnósticos, gestão e relacionamento com pacientes.',
    content: `<h2>IA Não é Ficção Científica</h2><p>Ferramentas de IA já estão em clínicas brasileiras para análise de imagens e triagem.</p>`,
    category: 'tecnologia-em-saude',
    categoryName: 'Tecnologia em Saúde',
    author: 'Equipe NexusMed',
    authorRole: 'Inovação & Tecnologia',
    date: '2026-03-03',
    readTime: 7,
    tags: ['IA', 'inteligência artificial', 'diagnóstico'],
    coverEmoji: '🤖',
  },
  {
    slug: 'seguranca-de-dados-clinica',
    title: 'Segurança de Dados na Clínica: Guia Prático para Proteger Prontuários',
    excerpt: 'Como proteger os dados dos seus pacientes contra vazamentos e violações da LGPD.',
    content: `<h2>O Cenário de Ameaças</h2><p>O setor de saúde foi o segundo mais atacado no Brasil em 2025.</p>`,
    category: 'tecnologia-em-saude',
    categoryName: 'Tecnologia em Saúde',
    author: 'Equipe NexusMed',
    authorRole: 'Segurança & Compliance',
    date: '2026-02-22',
    readTime: 8,
    tags: ['segurança', 'LGPD', 'cibersegurança'],
    coverEmoji: '🔒',
  },
  {
    slug: 'lgpd-clinicas-guia-pratico',
    title: 'LGPD para Clínicas: Guia Prático de Conformidade em 2026',
    excerpt: 'Tudo sobre proteção de dados de pacientes, consentimento e como evitar multas da ANPD.',
    content: `<h2>Por que a LGPD é Crítica</h2><p>Dados de saúde são sensíveis pela LGPD. Multas chegam a R$ 50 milhões por infração.</p>`,
    category: 'regulamentacao',
    categoryName: 'Regulamentação',
    author: 'Equipe NexusMed',
    authorRole: 'Jurídico & Compliance',
    date: '2026-03-05',
    readTime: 8,
    tags: ['LGPD', 'compliance', 'privacidade'],
    coverEmoji: '⚖️',
  },
  {
    slug: 'cfm-resolucoes-2026',
    title: 'CFM em 2026: As Resoluções que Mais Impactam sua Clínica',
    excerpt: 'Panorama das principais resoluções do CFM vigentes em 2026 e o que cada gestor precisa fazer.',
    content: `<h2>Por Que Acompanhar o CFM</h2><p>O CFM publicou mais de 60 resoluções desde 2020. Desconhecer não isenta o médico.</p>`,
    category: 'regulamentacao',
    categoryName: 'Regulamentação',
    author: 'Equipe NexusMed',
    authorRole: 'Jurídico & Compliance',
    date: '2026-03-09',
    readTime: 9,
    tags: ['CFM', 'resoluções', 'ética médica'],
    coverEmoji: '📜',
  },
  {
    slug: 'anvisa-clinicas-conformidade',
    title: 'ANVISA para Clínicas: Tudo Sobre Alvará Sanitário e Conformidade',
    excerpt: 'Como obter e manter o alvará sanitário, exigências de estrutura física e como evitar interdições.',
    content: `<h2>Alvará Sanitário é Obrigatório</h2><p>Toda clínica precisa de alvará sanitário emitido pela Vigilância Sanitária Municipal.</p>`,
    category: 'regulamentacao',
    categoryName: 'Regulamentação',
    author: 'Equipe NexusMed',
    authorRole: 'Jurídico & Compliance',
    date: '2026-02-18',
    readTime: 7,
    tags: ['ANVISA', 'alvará', 'vigilância sanitária'],
    coverEmoji: '🧪',
  },
  {
    slug: 'ans-convenios-direitos-clinicas',
    title: 'ANS e Convênios: Direitos e Obrigações das Clínicas Credenciadas',
    excerpt: 'O que a ANS garante para clínicas credenciadas: prazos de pagamento, regras de glosa e como acionar a agência.',
    content: `<h2>O Papel da ANS</h2><p>A ANS regula a relação entre operadoras e prestadores. Clínicas têm direitos garantidos que muitas desconhecem.</p>`,
    category: 'regulamentacao',
    categoryName: 'Regulamentação',
    author: 'Equipe NexusMed',
    authorRole: 'Faturamento & Convênios',
    date: '2026-02-10',
    readTime: 7,
    tags: ['ANS', 'convênios', 'credenciamento'],
    coverEmoji: '💳',
  },
  {
    slug: 'experiencia-do-paciente-5-estrategias',
    title: '5 Estratégias para Transformar a Experiência do Paciente na Sua Clínica',
    excerpt: 'Da recepção ao pós-consulta: como criar uma jornada memorável que gera indicações e fidelização.',
    content: `<h2>A Jornada Completa do Paciente</h2><p>A experiência começa antes da consulta e vai até o pós-atendimento. Cada ponto de contato importa.</p><h2>1. Agendamento Simples</h2><p>Ofereça agendamento online 24/7.</p><h2>2. Sala de Espera Humanizada</h2><p>Tempo de espera comunicado e Wi-Fi disponível.</p><h2>3. Comunicação Pós-Consulta</h2><p>Envie resumo via WhatsApp.</p><h2>4. Pesquisa de Satisfação</h2><p>NPS automático 24h após a consulta.</p><h2>5. Programa de Fidelidade</h2><p>Reconheça pacientes frequentes.</p>`,
    category: 'experiencia-do-paciente',
    categoryName: 'Experiência do Paciente',
    author: 'Equipe NexusMed',
    authorRole: 'Sucesso do Cliente',
    date: '2026-02-25',
    readTime: 6,
    tags: ['paciente', 'fidelização', 'NPS'],
    coverEmoji: '🤝',
  },
  {
    slug: 'nps-clinicas-como-usar',
    title: 'NPS para Clínicas: Como Medir e Usar a Satisfação do Paciente a seu Favor',
    excerpt: 'O que é NPS, como aplicar na clínica, interpretar os resultados e transformar pacientes satisfeitos em promotores da sua marca.',
    content: `<h2>O Que é NPS</h2><p>Net Promoter Score é a pergunta: "Em uma escala de 0 a 10, o quanto você indicaria nossa clínica a um amigo?" Simples, mas poderoso.</p><h2>Como Classificar as Respostas</h2><p>Promotores: 9-10. Neutros: 7-8. Detratores: 0-6. NPS = % Promotores - % Detratores.</p><h2>Quando Enviar</h2><p>Automatize o envio 24h após cada consulta por WhatsApp. A taxa de resposta é 3x maior do que e-mail.</p><h2>O Que Fazer com os Detratores</h2><p>Entre em contato pessoalmente dentro de 48h. Um detrator que tem o problema resolvido pode se tornar um promotor ainda mais fiel.</p><h2>Usando Promotores</h2><p>Convide promotores (nota 9-10) a deixar avaliação no Google Meu Negócio com um link direto. Isso melhora o ranqueamento local da clínica.</p>`,
    category: 'experiencia-do-paciente',
    categoryName: 'Experiência do Paciente',
    author: 'Equipe NexusMed',
    authorRole: 'Sucesso do Cliente',
    date: '2026-03-02',
    readTime: 6,
    tags: ['NPS', 'satisfação', 'fidelização'],
    coverEmoji: '⭐',
  },
  {
    slug: 'comunicacao-medico-paciente',
    title: 'Comunicação Médico-Paciente: Como Explicar Diagnósticos com Clareza',
    excerpt: 'Técnicas de comunicação em saúde para explicar diagnósticos complexos de forma simples, aumentar a adesão ao tratamento e construir confiança.',
    content: `<h2>Por Que a Comunicação Importa</h2><p>Pacientes que entendem seu diagnóstico aderem 3x mais ao tratamento e têm menos complicações. A comunicação eficaz é uma habilidade clínica tão importante quanto o conhecimento técnico.</p><h2>A Técnica "Teach-Back"</h2><p>Após explicar, peça ao paciente que repita com as próprias palavras o que entendeu. Isso revela lacunas de compreensão sem fazer o paciente se sentir ignorante.</p><h2>Linguagem Acessível</h2><p>Evite jargões médicos. Troque "hipertensão arterial sistêmica" por "pressão alta". Troque "cefaleia" por "dor de cabeça". O paciente precisa entender, não impressionar-se.</p><h2>O Documento de Orientações</h2><p>Envie um resumo escrito por WhatsApp após a consulta com: diagnóstico simplificado, medicações, próximos passos e quando retornar. Isso reduz 60% das dúvidas pós-consulta.</p>`,
    category: 'experiencia-do-paciente',
    categoryName: 'Experiência do Paciente',
    author: 'Equipe NexusMed',
    authorRole: 'Educação em Saúde',
    date: '2026-02-14',
    readTime: 7,
    tags: ['comunicação', 'paciente', 'adesão'],
    coverEmoji: '💬',
  },
  {
    slug: 'google-meu-negocio-clinicas',
    title: 'Google Meu Negócio para Clínicas: Guia Completo para Aparecer nas Buscas',
    excerpt: 'Como otimizar o perfil do Google Meu Negócio da sua clínica para atrair mais pacientes, melhorar avaliações e dominar buscas locais.',
    content: `<h2>Por Que o Google Meu Negócio é Essencial</h2><p>Mais de 77% dos pacientes pesquisam no Google antes de escolher uma clínica. Um perfil bem otimizado aparece no mapa e gera ligações e agendamentos diretamente.</p><h2>Informações Obrigatórias</h2><p>Preencha: nome correto, endereço exato, telefone atualizado, horário de funcionamento, site e categoria principal (ex: Clínica Médica).</p><h2>Fotos Fazem Diferença</h2><p>Perfis com fotos recebem 42% mais pedidos de rotas. Adicione fotos da fachada, recepção, consultórios e equipe.</p><h2>Gerenciando Avaliações</h2><p>Responda TODAS as avaliações — positivas e negativas. Resposta cordial a avaliação negativa mostra profissionalismo e muitas vezes reverte a percepção.</p>`,
    category: 'experiencia-do-paciente',
    categoryName: 'Experiência do Paciente',
    author: 'Equipe NexusMed',
    authorRole: 'Marketing Digital',
    date: '2026-01-30',
    readTime: 8,
    tags: ['Google', 'avaliações', 'captação'],
    coverEmoji: '📍',
  },
  {
    slug: 'marketing-medico-instagram',
    title: 'Marketing Médico no Instagram: O Que Pode e O Que Não Pode em 2026',
    excerpt: 'Guia completo das resoluções do CFM sobre publicidade médica e como construir presença digital ética.',
    content: `<h2>O CFM e as Redes Sociais</h2><p>A Resolução CFM 2.336/2023 atualizou as regras de publicidade médica para o ambiente digital.</p>`,
    category: 'marketing-medico',
    categoryName: 'Marketing Médico',
    author: 'Equipe NexusMed',
    authorRole: 'Marketing',
    date: '2026-02-20',
    readTime: 6,
    tags: ['CFM', 'Instagram', 'marketing'],
    coverEmoji: '📣',
  },
  {
    slug: 'gestao-de-equipe-clinica',
    title: 'Como Montar e Liderar uma Equipe de Alta Performance na Clínica',
    excerpt: 'Da contratação ao treinamento: estratégias para construir um time engajado e produtivo.',
    content: `<h2>Cultura Antes de Processos</h2><p>Defina os valores da clínica antes de contratar. Uma equipe alinhada performa melhor.</p>`,
    category: 'gestao-de-equipes',
    categoryName: 'Gestão de Equipes',
    author: 'Equipe NexusMed',
    authorRole: 'RH & Cultura',
    date: '2026-02-15',
    readTime: 7,
    tags: ['equipe', 'liderança', 'RH'],
    coverEmoji: '👥',
  },
];

export function getAllPosts(): Post[] {
  return POSTS.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getPostBySlug(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug);
}

export function getPostsByCategory(category: string): Post[] {
  return POSTS.filter((p) => p.category === category);
}
